"""B2-DIAG-001: physics/conditioning analysis of FE-D-M1 (no training, no network optimisation).
Writes results_batch2/reports/B2-DIAG-001_conditioning_FE-D-M1.{json,md}. Never overwrites.

    python scripts/conditioning_report.py
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from physref.conditioning import analyze, beam_spec  # noqa: E402
from physref.formulations.modal import galerkin_modal_system  # noqa: E402
from physref.provenance import git_state  # noqa: E402
from physref.safety import assert_safe_output  # noqa: E402

EXP = "B2-DIAG-001"


def main():
    spec, ref = beam_spec("FE-D-M1")
    conv = {"B0 paper (2pi, physical)": {"input_norm": "physical", "two_pi": True, "sigma_t": (10.0, 1.0)},
            "B1 D4 (no 2pi, standardised)": {"input_norm": "standardize", "two_pi": False, "sigma_t": (10.0, 1.0)}}
    rep = analyze(spec, ref, fourier=conv)
    rep["galerkin_modes"] = galerkin_modal_system(ref, 3)
    sha, dirty = git_state()
    rep["experiment_id"], rep["git_sha"], rep["git_dirty"] = EXP, sha, dirty
    out = assert_safe_output(REPO / "results_batch2" / "reports", strict=True, purpose=EXP)
    jp, mp = out / f"{EXP}_conditioning_FE-D-M1.json", out / f"{EXP}_conditioning_FE-D-M1.md"
    with open(jp, "x") as f:
        json.dump(rep, f, indent=2, default=str)
    s = rep["scales"]; tm = rep["term_magnitudes"]; nd = rep["nondimensionalization"]
    L = [f"# {EXP}: physics/conditioning analysis of FE-D-M1 (diagnostic only; no training)", "",
         f"git {sha[:12]}{' (dirty)' if dirty else ''}. Generated by `scripts/conditioning_report.py`.", "",
         "## Characteristic scales", "", "| quantity | value |", "|---|---|"]
    L += [f"| {k} | {v:.6g} |" if isinstance(v, float) else f"| {k} | {v} |" for k, v in s.items()]
    L += ["", "## Term magnitudes for a modal field (|a_ij| beta1^i w1^j A0)", "", "| term | magnitude | ratio to max |", "|---|---|---|"]
    L += [f"| {k} | {v:.4g} | {tm['ratios_to_max'][k]:.4g} |" for k, v in tm["magnitudes"].items()]
    L += ["", "## Nondimensionalization candidates (coefficients normalised by the u_tt coefficient)", "",
          "| scaling | a40 | a02 | a01 | xi range | tau range | coeff spread |", "|---|---|---|---|---|---|---|"]
    for k, v in nd.items():
        c = v["coeffs"]
        L.append(f"| {k} | {c['a40']:.4g} | {c['a02']:.4g} | {c['a01']:.4g} | {v['xi_range']:.4g} | {v['tau_range']:.4g} | {v['coeff_spread']:.4g} |")
    L += ["", "**Invariant:** no rescaling changes the dimensionless groups N_cycles = omega_d T / 2pi = "
          f"{s['cycles_in_window']:.2f}, zeta = {s['damping_ratio']:.4f} and beta1 L = {s['wavelength_ratio_L_beta1']:.4f}. "
          "Rescaling redistributes coefficient magnitudes; it cannot shorten the temporal propagation length.", "",
          "## Hard-ansatz time-factor conditioning (required network output scale near t = 0)", "",
          "| time factor | g''(0) | N* scale |", "|---|---|---|"]
    L += [f"| {k} | {v['g2_at_0']:.4g} | {v['N_star_scale']:.4g} |" for k, v in rep["hard_ansatz"].items()]
    L += ["", "## Temporal Fourier-feature coverage of omega_d (expected counts out of m = 100)", "",
          "| convention | sigma_t | expected count >= omega_d |", "|---|---|---|"]
    for k, lst in rep["fourier_coverage_t"].items():
        L += [f"| {k} | {d['sigma']:g} | {d['expected_count']:.3g} |" for d in lst]
    L += ["", "Seeded draws measured in Batch 1 (`references/batch1/tables/stage01_fourier_support_FE-D-M1.csv`): B0 3/100, B1 0/100. "
          "B1 nevertheless reproduced the correct frequency (-0.1 %) in the cycles it covered, so the high frequency is "
          "synthesised by the tanh trunk, not supplied by the features.", "",
          "## Galerkin modal system (exact fixed-fixed modes)", "", "| n | beta_n [1/m] | w_n^2 Galerkin | w_n^2 = c2 beta^4 | q_n(0) |", "|---|---|---|---|---|"]
    L += [f"| {m['n']} | {m['beta']:.6f} | {m['omega2_galerkin']:.6g} | {m['omega2_closed']:.6g} | {m['q0']:.3g} |" for m in rep["galerkin_modes"]]
    sc = rep["spectral_content_midspan"]
    L += ["", f"Mid-span spectral content of the exact solution: dominant {sc['dominant_Hz']:.3f} Hz, 99 % energy below {sc['band_99pct_Hz']:.3f} Hz."]
    with open(mp, "x") as f:
        f.write("\n".join(L) + "\n")
    print(mp)


if __name__ == "__main__":
    main()
